lora:
  alpha: 16
  bias: none
  dropout: 0.05
  r: 8
  target_modules:
  - q_proj
  - k_proj
  - v_proj
  - o_proj
  - gate_proj
  - up_proj
  - down_proj
  task_type: CAUSAL_LM
model:
  model_type: qwen2
  name_or_path: ./models/qwen2.5-0.5b-instruct
  torch_dtype: float32
  trust_remote_code: true
quantization:
  bnb_4bit_compute_dtype: float32
  bnb_4bit_quant_type: nf4
  bnb_4bit_use_double_quant: true
  use_4bit: false
